### ISSUE TITLE
v1.0.7 issue with ws declarations

### ISSUE THREAD

**Issue by vitaly-t** [ccxt/node-binance-api#938]
After upgrading from v1.0.6 to v1.0.7 I am getting this error on compilation:

```
node_modules/node-binance-api/dist/node-binance-api.d.ts:1:23 - error TS7016: Could not find a declaration file for module 'ws'. 'C:/Projects/piglet/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

1 import WebSocket from 'ws';
                        ~~~~


Found 1 error in node_modules/node-binance-api/dist/node-binance-api.d.ts:1
```

It's a new issue, introduced in the latest version.

**Comment by carlosmiei** [comment]
@vitaly-t Thanks for reporting it, this is happening because we typed a variable with using `Websockets` types, but we can remove it no problem.

**Comment by carlosmiei** [comment]
@vitaly-t can you please upgrade to the latest (1.0.8) and try again? it should be working now

**Comment by vitaly-t** [comment]
Yep, v1.0.8 is fine now. Thank you for such a quick fix!
